# UKWA Heritrix
ukwa-heritrix:
  build: ../ukwa-heritrix
  volumes:
    - ./jobs:/jobs
  ports:
    - "8443:8443"
  links:
    - clamd
    - rabbitmq
    - monitrix
  volumes_from:
    - dvc:rw

# Data Volume Container
# - This is the recommended way to share a data volume between containers.
dvc:
  image: busybox
  volumes:
    - ./data:/data

# Clamd virus scanning Service
clamd:
  build: ../clamd
  ports:
    - "3310:3310"

# RabbitMQ
rabbitmq:
  image: rabbitmq:3.5-management
  ports:
    - "15672:15672"  # management port (guest:guest)
    - "5672:5672"   # amqp port
    - "25672:25672" # cluster port
  log_driver: none

# PhantomJS web page rendering service
webrender:
  build: ../webrender-phantomjs
  ports:
    - "8000:8000"

# HAR Daemon that connects Heritrix to Webrender via RabbitMQ
har-daemon:
  build: ../webrender-har-daemon
  environment:
    - "AMQP_URL=amqp://guest:guest@rabbitmq:5672/%2f"
  links:
    - rabbitmq
    - webrender
  volumes_from:
    - dvc:rw

# Monitrix, built on ELK by extending Logstash to support Heritrix logs.
monitrix:
  build: ../monitrix
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5000:5000"
    - "5044:5044"

# OpenWayback, based loosely on UNB Libraries Dockerfile
openwayback:
  build: ../openwayback
  ports:
    - "8080:8080"
  environment:
    - WAYBACK_BASEDIR=/data
    - WAYBACK_URL_HOST=192.168.99.100
  volumes_from:
    - dvc:ro
